pr:
  - master
  - develop

strategy:
  matrix:
    linux:
      imageName: "ubuntu-16.04"
    mac:
      imageName: "macos-10.13"
    windows:
      imageName: "vs2017-win2016"

pool:
  vmImage: $(imageName)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "12.13.0"
    displayName: "Install Node.js"

  - bash: |
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    displayName: Start xvfb
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

  - script: |
      npm install -g vsce
      npm install
    displayName: Install dependencies and vsce

  - script: |
      npm run tslint
    displayName: Run TSLint Checks

  - script: |
      npm run compile
    displayName: Compile Sources

  - script: |
      npm test --silent
    displayName: Run Unit Tests

  - script: |
      # node scripts/genAiKey.js
      vsce package
    displayName: Build VSIX Package
