trigger:
- master
- develop

pr: none

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.14'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:

  - template: common/setup_steps.yml
  - template: common/compile_steps.yml
  - template: common/check_steps.yml
  - template: common/test_steps.yml
  - template: common/genvsix_steps.yml
