trigger: none

pr:
- main
- dev

stages:
- stage: CredScan
  jobs:
    - job: run_credscan
      displayName: 'Run CredScan'
      pool:
        vmImage: 'windows-latest'
      steps:
        # cred scan
        - task: CredScan@3
          displayName: 'Run CredScan'
          inputs:
            outputFormat: 'pre'
            scanFolder: '$(Build.SourcesDirectory)'

        - task: PostAnalysis@1
          inputs:
            AllTools: false
            APIScan: false
            BinSkim: false
            CodesignValidation: false
            CredScan: true
            FortifySCA: false
            FxCop: false
            ModernCop: false
            PoliCheck: false
            RoslynAnalyzers: false
            SDLNativeRules: false
            Semmle: false
            TSLint: false
            ToolLogsNotFoundAction: 'Standard'

- stage: Test
  dependsOn: []
  jobs:
  - job: run_tests
    displayName: 'Run tests'
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-latest'
        mac:
          imageName: 'macos-latest'
        windows:
          imageName: 'windows-latest'

    pool:
      vmImage: $(imageName)
    steps:
      - template: common/setup_steps.yml
      - template: common/compile_steps.yml
      - template: common/test_steps.yml
