schedules:
- cron: '0 19 * * *'
  displayName: 'Nightly build and test'
  branches:
    include:
    - dev
  always: false

trigger: none
pr: none

stages:
- stage: SDL
  jobs:
    - job: sdl_checks
      displayName: 'SDL checks'
      pool:
        vmImage: 'windows-latest'
      steps:
        - template: common/sdl_steps.yml

- stage: Test
  dependsOn: ['SDL']
  jobs:
  - job: run_tests
    displayName: 'Run tests'
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-latest'
        mac:
          imageName: 'macos-latest'
        windows:
          imageName: 'windows-latest'
    pool:
      vmImage: $(imageName)
    steps:
      - template: common/setup_steps.yml
      - template: common/compile_steps.yml
      - template: common/test_steps.yml