schedules:
- cron: '0 20 * * *'
  displayName: Nightly build on 4:00 AM (GMT+8)
  branches:
    include:
    - develop
  always: true # no matter whether there exists a new push to develop, run nightly anyway.

trigger: none
pr: none

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.14'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

variables:
- template: common/variables.yml

steps:

  - template: common/setup_steps.yml
  - template: common/compile_steps.yml
  - template: common/check_steps.yml
  - template: common/test_steps.yml

  # modify package.json for release candidates
  # including k/v pairs in cli arguments, remove trailing -rc if presents
  - script: |
      node scripts/modifyPackageJson.js name $(nightly_extension_name) displayName "$(test_display_name)" aiKey ${TEST_AIKEY} publisher $(nightly_publisher)
    displayName: Modify package.json for release candidates

  - template: common/package_steps.yml

  # publish vsix to marketplace for release candidates
  - bash: yes | vsce unpublish -p $MARKETPLACE_TOKEN $(nightly_publisher).$(nightly_extension_name) && vsce publish -p $MARKETPLACE_TOKEN --packagePath *.vsix
    displayName: Deploy release candidates to marketplace
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))
    env:
      MARKETPLACE_TOKEN: $(iotdevexbuild_marketplace_token)
