trigger: none
pr:
- use_token_of_vsciotci

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'

pool:
  vmImage: $(imageName)

variables:
- template: common/variables.yml

steps:

  - template: common/setup_steps.yml
  - template: common/compile_steps.yml
  - template: common/check_steps.yml
  - template: common/test_steps.yml

  - template: common/package_steps.yml




  - task: GitHubRelease@0
    displayName: Deploy Releases or Release Candidates to GitHub Release
    inputs:
      gitHubConnection: 'vsciotci_github_pat_pnp_authoring'
      repositoryName: '$(Build.Repository.Name)'
      action: 'create'
      target: '$(Build.SourceVersion)'
      isPreRelease: $(is_rc)
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))
